In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/JeffSackmann/tennis_MatchChartingProject/master/charting-m-points-from-2017.csv', encoding= 'unicode_escape')
df.head()

/tmp/ipykernel_7151/3110691026.py:1: DtypeWarning: Columns (8,9,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://raw.githubusercontent.com/JeffSackmann/tennis_MatchChartingProject/master/charting-m-points-from-2017.csv', encoding= 'unicode_escape')

,match_id,Pt,Set1,Set2,Gm1,Gm2,Pts,Gm#,TbSet,TB?,...,2ndIn,isAce,isUnret,isRallyWinner,isForced,isUnforced,isDouble,PtWinner,isSvrWinner,rallyCount
0,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,1,0,0,0,0,0-0,1 (1),1,0,...,0.0,False,False,False,False,False,True,2,0,0
1,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,2,0,0,0,0,0-15,1 (2),1,0,...,NaN,False,True,False,False,False,False,1,1,1
2,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,3,0,0,0,0,15-15,1 (3),1,0,...,1.0,False,False,False,True,False,False,2,0,2
3,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,4,0,0,0,0,15-30,1 (4),1,0,...,NaN,False,False,False,True,False,False,1,1,1
4,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,5,0,0,0,0,30-30,1 (5),1,0,...,NaN,False,True,False,False,False,False,1,1,1

In [28]:
# Novak Djokovic vs Andy Murray
nd_am = df[df['match_id'] == '20170107-M-Doha-F-Novak_Djokovic-Andy_Murray']

nd_am = nd_am[['Pt', 'Svr', '1st', '2nd', 'isAce', 'isUnret', 'isRallyWinner', 
               'isForced', 'isUnforced', 'isDouble', 'PtWinner', 'rallyCount']]
nd_am.set_index('Pt', inplace=True)

nd_am['Type_Srv_1st'] = nd_am.iloc[:, 1].str[0]
nd_am['Type_Srv_2st'] = nd_am.iloc[:, 2].str[0]
nd_am['Type_Srv_2st'].fillna(0, inplace=True)

# proximo passo
# devolucao -> se tiver menos de 3 caracteres, o ponto nao seguiu

nd_am

,Svr,1st,2nd,isAce,isUnret,isRallyWinner,isForced,isUnforced,isDouble,PtWinner,rallyCount,Type_Srv_1st,Type_Srv_2st
Pt,,,,,,,,,,,,,
1,1,6s39f2f2b2f1f1f3n@,NaN,False,False,False,False,True,False,1,7,6,0
2,1,4b37y3n@,NaN,False,False,False,False,True,False,2,2,4,0
3,1,6s37b+1f1v1*,NaN,False,False,True,False,False,False,1,5,6,0
4,1,4b38b2f1f3d@,NaN,False,False,False,False,True,False,2,4,4,0
5,1,6w,4f18f3b3b1f1w#,False,False,False,True,False,False,1,5,6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,1,6f38b3b3b2f3b3s3f3b3f3b3f2f1f1f2s3s3b1n@,NaN,False,False,False,False,True,False,2,18,6,0
191,1,6w,5b39b2b2f3b3b3s3b3b3b3b3s3b3b1f1f1f2n@,False,False,False,False,True,False,1,17,6,5
192,1,4b39b3b3n@,NaN,False,False,False,False,True,False,1,3,4,0
193,1,4d,4f19f3b3b3b1f2b3s3f3b3b3b2b3n@,False,False,False,False,True,False,1,13,4,4
194,1,6n,5f39b2f3b1f1f1f2b3b2b1f1f1f2b3b3b1f1f3s3f+-1*,False,False,True,False,False,False,1,21,6,5

KeyError: "['Pt'] not in index"

,Svr,1st,2nd,isAce,isUnret,isRallyWinner,isForced,isUnforced,isDouble,PtWinner,rallyCount,Type_Srv_1st
Pt,,,,,,,,,,,,
1,1,6s39f2f2b2f1f1f3n@,NaN,False,False,False,False,True,False,1,7,6
2,1,4b37y3n@,NaN,False,False,False,False,True,False,2,2,4
3,1,6s37b+1f1v1*,NaN,False,False,True,False,False,False,1,5,6
4,1,4b38b2f1f3d@,NaN,False,False,False,False,True,False,2,4,4
5,1,6w,4f18f3b3b1f1w#,False,False,False,True,False,False,1,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...
190,1,6f38b3b3b2f3b3s3f3b3f3b3f2f1f1f2s3s3b1n@,NaN,False,False,False,False,True,False,2,18,6
191,1,6w,5b39b2b2f3b3b3s3b3b3b3b3s3b3b1f1f1f2n@,False,False,False,False,True,False,1,17,6
192,1,4b39b3b3n@,NaN,False,False,False,False,True,False,1,3,4
193,1,4d,4f19f3b3b3b1f2b3s3f3b3b3b2b3n@,False,False,False,False,True,False,1,13,4
194,1,6n,5f39b2f3b1f1f1f2b3b2b1f1f1f2b3b3b1f1f3s3f+-1*,False,False,True,False,False,False,1,21,6