In [4]:
import pandas as pd

In [10]:
df = pd.read_csv('charting-m-points-from-2017.csv', encoding= 'unicode_escape')
df.head()

/var/folders/wm/hgzc7rpn43d892__g_f3yd3m0000gn/T/ipykernel_37902/1173247186.py:1: DtypeWarning: Columns (8,9,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('charting-m-points-from-2017.csv', encoding= 'unicode_escape')

,match_id,Pt,Set1,Set2,Gm1,Gm2,Pts,Gm#,TbSet,TB?,...,2ndIn,isAce,isUnret,isRallyWinner,isForced,isUnforced,isDouble,PtWinner,isSvrWinner,rallyCount
0,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,1,0,0,0,0,0-0,1 (1),1,0,...,0.0,False,False,False,False,False,True,2,0,0
1,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,2,0,0,0,0,0-15,1 (2),1,0,...,NaN,False,True,False,False,False,False,1,1,1
2,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,3,0,0,0,0,15-15,1 (3),1,0,...,1.0,False,False,False,True,False,False,2,0,2
3,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,4,0,0,0,0,15-30,1 (4),1,0,...,NaN,False,False,False,True,False,False,1,1,1
4,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,5,0,0,0,0,30-30,1 (5),1,0,...,NaN,False,True,False,False,False,False,1,1,1

In [7]:
meaning_char = pd.read_csv('https://raw.githubusercontent.com/eduardoscovino/tennis-analytics/master/code_map.csv',
                           encoding= 'unicode_escape', sep=';')
meaning_char

   code                                               info           remark
0     4                                               wide  serve direction
1     5                                               body  serve direction
2     6                                         down the T  serve direction
3     f                                           forehand      common shot
4     b                                           backhand      common shot
5     s                                     backhand slice      common shot
6     r                                     forehand slice      common shot
7     @                                     unforced error  how point ended
8     #                                       forced error  how point ended
9     *                                             winner  how point ended
10    n                                                net    type of error
11    w                                               wide    type of error
12    d                                               deep    type of error
13    x                                      wide and deep    type of error
14    v                                    forehand volley       other shot
15    l                                                lob       other shot
16    o                                     overhead/smash       other shot
17    1  to a right-handerÂ’s forehand (or a leftyÂ’s bac...   shot direction
18    2                                    down the middle   shot direction
19    3                       to a right-handerÂ’s backhand   shot direction
20    7                                            shallow     return depth
21    8                                    moderately deep     return depth
22    9                                         verry deep     return depth
23    +                                     approach shots   court position
24    -                                     hit at the net   court position
25    =                                hit at the baseline   court position

In [11]:
print(df.columns)

Index(['match_id', 'Pt', 'Set1', 'Set2', 'Gm1', 'Gm2', 'Pts', 'Gm#', 'TbSet',
       'TB?', 'TBpt', 'Svr', 'Ret', 'Serving', '1st', '2nd', 'Notes', '1stSV',
       '2ndSV', '1stIn', '2ndIn', 'isAce', 'isUnret', 'isRallyWinner',
       'isForced', 'isUnforced', 'isDouble', 'PtWinner', 'isSvrWinner',
       'rallyCount'],
      dtype='object')

In [19]:
df[['1st', '2nd']].head(25)

               1st                                                2nd
0               4d                                                 5n
1               4#                                                NaN
2               4n                                           5f29f3n#
3            6f3x#                                                NaN
4               4#                                                NaN
5               6w                                                 4x
6               4*                                                NaN
7               6d                                                 4d
8               4w                   6b27f38b27f38b38b39b38b39b38f1d@
9               6n                                     4b39f19f28f38*
10              4w                         6b18f38b38b39b38f38s18f39*
11              4n                               4b38b28f17f19f29f1n@
12              4w  5b17f39b38b38s39f38b39f38b19f19f18f18f19f28b28...
13     6r29f18f1n@                                                NaN
14              4n                                                 5n
15              6*                                                NaN
16              4n                                6b38b38b28f+18f17w#
17              6w                                              4b3d#
18              4*                                                NaN
19  4b38b39b38f38*                                                NaN
20            4f1#                                                NaN
21              4*                                                NaN
22        4r28f38*                                                NaN
23              5n                                           5b38f1n@
24              6d                                    5b27f18f29f!2d@

In [46]:
#Spliting Serve and Return
df['RETURN'] = df.loc[:, '2nd']
df['RETURN'].fillna(df.loc[:, '1st'], inplace=True)


df['Serve'] = df.loc[:, 'RETURN'].str[0:1]

df['RETURN'] = df['RETURN'].str[1:]

df.head()

,match_id,Pt,Set1,Set2,Gm1,Gm2,Pts,Gm#,TbSet,TB?,...,isUnret,isRallyWinner,isForced,isUnforced,isDouble,PtWinner,isSvrWinner,rallyCount,RETURN,Serve
0,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,1,0,0,0,0,0-0,1 (1),1,0,...,False,False,False,False,True,2,0,0,n,5
1,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,2,0,0,0,0,0-15,1 (2),1,0,...,True,False,False,False,False,1,1,1,#,4
2,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,3,0,0,0,0,15-15,1 (3),1,0,...,False,False,True,False,False,2,0,2,f29f3n#,5
3,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,4,0,0,0,0,15-30,1 (4),1,0,...,False,False,True,False,False,1,1,1,f3x#,6
4,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,5,0,0,0,0,30-30,1 (5),1,0,...,True,False,False,False,False,1,1,1,#,4

In [47]:
#Spliting every shot

df['RETURN'] = df['RETURN'].str.replace('f','0f').str.replace('b','0b').str.replace('s','0s').str.replace('r','0r').str.split('0')
df.head(25)

,match_id,Pt,Set1,Set2,Gm1,Gm2,Pts,Gm#,TbSet,TB?,...,isUnret,isRallyWinner,isForced,isUnforced,isDouble,PtWinner,isSvrWinner,rallyCount,RETURN,Serve
0,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,1,0,0,0,0,0-0,1 (1),1,0,...,False,False,False,False,True,2,0,0,[n],5
1,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,2,0,0,0,0,0-15,1 (2),1,0,...,True,False,False,False,False,1,1,1,[#],4
2,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,3,0,0,0,0,15-15,1 (3),1,0,...,False,False,True,False,False,2,0,2,"[, f29, f3n#]",5
3,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,4,0,0,0,0,15-30,1 (4),1,0,...,False,False,True,False,False,1,1,1,"[, f3x#]",6
4,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,5,0,0,0,0,30-30,1 (5),1,0,...,True,False,False,False,False,1,1,1,[#],4
5,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,6,0,0,0,0,40-30,1 (6),1,0,...,False,False,False,False,True,2,0,0,[x],4
6,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,7,0,0,0,0,40-40,1 (7),1,0,...,False,False,False,False,False,1,1,1,[*],4
7,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,8,0,0,0,0,AD-40,1 (8),1,0,...,False,False,False,False,True,2,0,0,[d],4
8,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,9,0,0,0,0,40-40,1 (9),1,0,...,False,False,False,True,False,2,0,10,"[, b27, f38, b27, f38, b38, b39, b38, b39, b38...",6
9,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,10,0,0,0,0,40-AD,1 (10),1,0,...,False,True,False,False,False,1,1,5,"[, b39, f19, f28, f38*]",4
10,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,11,0,0,0,0,40-40,1 (11),1,0,...,False,True,False,False,False,1,1,9,"[, b18, f38, b38, b39, b38, f38, s18, f39*]",6
11,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,12,0,0,0,0,AD-40,1 (12),1,0,...,False,False,False,True,False,2,0,6,"[, b38, b28, f17, f19, f29, f1n@]",4
12,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,13,0,0,0,0,40-40,1 (13),1,0,...,False,True,False,False,False,2,0,22,"[, b17, f39, b38, b38, s39, f38, b39, f38, b19...",5
13,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,14,0,0,0,0,40-AD,1 (14),1,0,...,False,False,False,True,False,1,1,3,"[, r29, f18, f1n@]",6
14,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,15,0,0,0,0,40-40,1 (15),1,0,...,False,False,False,False,True,2,0,0,[n],5
15,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,16,0,0,0,0,40-AD,1 (16),1,0,...,False,False,False,False,False,1,1,1,[*],6
16,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,17,0,0,0,0,40-40,1 (17),1,0,...,False,False,True,False,False,1,1,5,"[, b38, b38, b28, f+18, f17w#]",6
17,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,18,0,0,0,0,AD-40,1 (18),1,0,...,False,False,True,False,False,1,1,1,"[, b3d#]",4
18,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,19,0,0,1,0,0-0,2 (1),1,0,...,False,False,False,False,False,2,1,1,[*],4
19,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,20,0,0,1,0,15-0,2 (2),1,0,...,False,True,False,False,False,2,1,5,"[, b38, b39, b38, f38*]",4
20,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,21,0,0,1,0,30-0,2 (3),1,0,...,False,False,True,False,False,2,1,1,"[, f1#]",4
21,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,22,0,0,1,0,40-0,2 (4),1,0,...,False,False,False,False,False,2,1,1,[*],4
22,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,23,0,0,1,1,0-0,3 (1),1,0,...,False,True,False,False,False,1,1,3,"[, r28, f38*]",4
23,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,24,0,0,1,1,15-0,3 (2),1,0,...,False,False,False,True,False,2,0,2,"[, b38, f1n@]",5
24,20221123-M-Davis_Cup_Finals-QF-Marin_Cilic-Pab...,25,0,0,1,1,15-15,3 (3),1,0,...,False,False,False,True,False,2,0,4,"[, b27, f18, f29, f!2d@]",5

In [51]:
pd.DataFrame(df['RETURN'].tolist(), index = df.index)

,0,1,2,3,4,5,6,7,8,9,...,74,75,76,77,78,79,80,81,82,83
0,n,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,#,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,,f29,f3n#,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,,f3x#,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,#,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295348,,b1,b1,f1,b1,f1*,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
295349,,f1,b2,b3d@,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
295350,d,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
295351,,s1,f1,f2n#,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
295352,,s2n#,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None